### ISSUE TITLE
Going to JSPM package manager throws an error

### ISSUE THREAD

**Issue by Ronmenator** [monterey-framework/monterey#371] opened 2016-10-06 14:19 UTC
### Intention

**I'm submitting a bug report**  

### Environment

* **Operating System:**
![image](https://cloud.githubusercontent.com/assets/6628234/19155808/ad6c85d0-8b94-11e6-878a-659a381efd4c.png)

* **Node Version:**
v6.4.0

* **NPM Version:**
3.10.6

* **Project name**
V-Corp
* **Project path:**
D:\VCorp\validcorp
* **NodeJS:**
6.5.0
* **NPM:**
3.10.8
* **Electron:**
1.4.1
* **Chrome:**
53.0.2785.113
* **Operating system:**
win32
* **Project is using JSPM**
* **JSPM version:**
0.16.15
* **Config.js path:**
D:\VCorp\validcorp\config.js
* **Project is using Gulp**
* **gulpfile.js path:**
D:\VCorp\validcorp\gulpfile.js
* **Project is using Typings**
* **typings.json path:**
D:\VCorp\validcorp\typings.json

### Description
**Current behavior:**  
Throws an error if I click on JSPM Package Manager
![image](https://cloud.githubusercontent.com/assets/6628234/19155765/852e6fd4-8b94-11e6-907f-0c8d8fae5929.png)

### Logs

[2016-010-06.txt](https://github.com/monterey-framework/monterey/files/513959/2016-010-06.txt)

**Comment by JeroenVinke** [comment] 2016-10-06 15:07
Thanks for reporting this 👍 

I was able to reproduce it by adding a space character in the path of Monterey:

![image](https://cloud.githubusercontent.com/assets/2189477/19157866/fb5f8c54-8be6-11e6-9408-ad4b497d7c61.png)

So this seems to be caused by the space in your path (`C:/Users/Ronnie Bernard/`)

Not sure yet what component is at fault here (could be Monterey but it could also be one of the libraries we use), but will definitely check that out

**Comment by JeroenVinke** [comment] 2016-10-06 19:24
we'll do some additional testing and will let you know when this fix is released

**Comment by Ronmenator** [comment] 2016-10-06 21:18
No problem, thanks

**Comment by JeroenVinke** [comment] 2016-10-09 07:17
@Ronmenator This has been released as v0.4.7. When you start Monterey it will download the update and after a restart of Monterey it will be installed. A message about this will popup in the top right corner of Monterey 

The installed version can be found in the About dialog:
![image](https://cloud.githubusercontent.com/assets/2189477/19218691/f6b20120-8e00-11e6-956c-4e5c2ed6dd25.png)

**Closed by JeroenVinke** 2016-10-09 07:17 UTC
Labels: bug

**Comment by Ronmenator** [comment] 2016-10-09 14:49
Thank you for the fix
