### ISSUE TITLE
Ease of use issue

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#270] opened 2016-09-02 18:14 UTC
This discussion belongs to the [managing existing applications](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/managing_existing_application.html) chapter

1. Started Monterey app
2. Added some existing project
3. Invoked the task manager. Here I felt safe that it is a meaningful thing to do as I know that this project was already built; it would be nice to provide this indication as a part of the left side grid entry

 ![image](https://cloud.githubusercontent.com/assets/2712405/18213635/329fb346-7117-11e6-8af3-17254cc81419.png)

After this step, I found the following errors being saved:

```
TypeError: Cannot read property 'animatableElement' of undefined
    at getAnimatableElement (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.1/aurelia-templating.js:1601:13)
    at ViewSlot.animateView (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.1/aurelia-templating.js:1640:31)
    at ViewSlot.removeAt (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.1/aurelia-templating.js:1842:30)
    at Repeat.removeView (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:284:28)
    at ArrayRepeatStrategy._runSplices (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/array-repeat-strategy.js:199:38)
    at ArrayRepeatStrategy.instanceMutated (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/array-repeat-strategy.js:166:31)
    at Repeat.handleCollectionMutated (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:172:21)
    at Repeat.call (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:116:20)
    at ModifyArrayObserver.callSubscribers (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.3/aurelia-binding.js:366:19)
    at ModifyArrayObserver.call (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.3/aurelia-binding.js:980:14)
```
<br>
 Not sure what would be the criteria for using the Task manager tile versus the Toolbar Task manager button - I used the Toolbar resident Task bar button to move to the next step.

**Comment by JeroenVinke** [comment] 2016-09-02 20:26
(the error is caused by https://github.com/monterey-framework/monterey/issues/263)

**Comment by adriatic** [comment] 2016-09-02 20:35
Are you sure? I did not do anything "quickly" that would cause a problems described in https://github.com/monterey-framework/monterey/issues/263

**Comment by JeroenVinke** [comment] 2016-09-02 20:56
Yes, I was able to reproduce the issue (something about it loading the tasks and in the mean time clicking on a running task). Should be fixed now

**Comment by adriatic** [comment] 2016-09-02 21:00
Wonderful

**Comment by JeroenVinke** [comment] 2016-09-11 18:19
Tracking in https://github.com/monterey-framework/monterey/issues/270

**Closed by JeroenVinke** 2016-09-11 18:19 UTC
