### ISSUE TITLE
dotnet core on OSX

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#335] opened 2016-09-21 23:26 UTC
### Intention

**I'm submitting a feature request**  

Similar to https://github.com/monterey-framework/monterey/issues/333, running the `skeleton-esnext-aspnetcore` sample results with the error notice asking whether the `dotnet` was installed.

So, I realized that I completely forgot how to install that component (other than installing VS code on my OSX) so we need to explain this situation a lot better.

**Comment by Thanood** [comment] 2016-09-22 07:41
Just because .Net Core confused me a little (name changes, overlapping with some "web tools" for vs)..
It's this right? https://www.microsoft.com/net/core#macos

**Comment by adriatic** [comment] 2016-09-22 12:39
@Thanood - I believe that this is what I was after, yes. My initial comment was written in frustration that I was not able to find it. It is indeed mentioned **[here](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-aspnetcore/src/skeleton)**. 

#### I will update the User manual to explain this in a very clear way

**Comment by adriatic** [comment] 2016-09-22 20:34
Having successfully installed `dotnet` as described in https://www.microsoft.com/net/core#macos I installed the latest Monterey (0.4.1). Starting it, I selected the `skeleton-esnext-aspnetcore` built yesterday (it failed to run because of not having `dotnet`, installed.

I was under the impression that just a click on the **`Run`** tile would result in seeing the app run - however, I got this:

![image](https://cloud.githubusercontent.com/assets/2712405/18765133/5cf7798c-80e2-11e6-85a2-3bc1a6df9d09.png)

I believe that this is a bug/

**Comment by JeroenVinke** [comment] 2016-09-23 06:55
Now you just need to install gulp ;) `npm install gulp -g`

**Comment by Thanood** [comment] 2016-09-23 08:04
It's referring to the local gulp. It's behind the red line, but also the command suggests it (no `-g`)..
So this would also happen when the `npm install` task fails. Or if it's not run. :smiley:

**Comment by JeroenVinke** [comment] 2016-09-23 08:51
ah yes, thanks @Thanood  👍 

I agree that it's likely that the node modules were not installed. I cannot reproduce this on windows or mac:

![image](https://cloud.githubusercontent.com/assets/2189477/18779961/994fb770-817b-11e6-86b9-8ebc3bffa05e.png)

So we need more info I think

**Comment by Thanood** [comment] 2016-09-23 08:57
I've tried to install a skeleton yesterday and totally failed to notice that `npm install` didn't finish. I only noticed that in NPM view not all packages were displayed as "installed".

The problem was actually vscode locking some directories. My point is, though: It might be a good idea to highlight NPM errors some more.

**Comment by JeroenVinke** [comment] 2016-09-23 09:04
I wonder if we should stop all queued tasks when the "parent" task fails. For example, when `npm install` fails, we would cancel all other queued tasks, because they all wait for npm install.

**Comment by JeroenVinke** [comment] 2016-09-23 09:04
BTW, can you share the monterey log of that day?

**Comment by Thanood** [comment] 2016-09-23 09:52
It's at home. I'll look it up when I get there.

**Comment by JeroenVinke** [comment] 2016-09-23 09:54
:+1: also there may be a npm-debug.log file in the project directory (Apparently npm creates those files when npm install fails)

**Comment by Thanood** [comment] 2016-09-23 10:01
Yes, I hope both are still there because I closed vscode, tried it again and then it worked.

**Comment by JeroenVinke** [comment] 2016-09-23 10:25
Interesting. First we need to make sure that the user knows it had failed to run npm install, and all others queued tasks need to be cancelled.

Then the user should be able to restart the install  process. The treelist you see at the end of the scaffolding wizard can be used to install existing projects as well. We can create an install tile that brings this screen up

**Comment by adriatic** [comment] 2016-09-23 13:40
A comment on[ @JeroenVinke's comment](https://github.com/monterey-framework/monterey/issues/335#issuecomment-249116837)

> Now you just need to install gulp ;) npm install gulp -g

You applied the "wink" emoji to this comment, so I would guess that you realized how your "advice" is not a serious one: why would I have to run `npm install -g gulp` when I did that already long time ago. As @Thanood observed, the Gulp issued error message was to install `local gulp`.

### More important point is this: 
why did this error took place? I tried to apply the `Run` button on a three days old application that was then (three days ago) built and run perfectly normal. I still have this application saved and will try it again with the most current Monterey later todat

**Comment by adriatic** [comment] 2016-09-23 13:55
> I wonder if we should stop all queued tasks when the "parent" task fails. For example, when npm install fails, we would cancel all other queued tasks, because they all wait for npm install.

### Absolutely
It would be nice to issue the relevant explanation as well.

**Comment by Thanood** [comment] 2016-09-25 11:15
@JeroenVinke No errors in my log file from that day. I guess it's because it worked the second try.

Anyway, here's the log file:
```
type,id,date,msg"info","monterey","2016-09-22T18:12:15.569Z","application started"
"info","aurelia","2016-09-22T18:12:15.705Z","Aurelia Starting"
"info","aurelia","2016-09-22T18:12:15.947Z","Aurelia Started"
"info","updater","2016-09-22T18:12:16.075Z","current version: 0.4.0"
"info","updater","2016-09-22T18:12:16.075Z","using update feed url: https://nuts.jeroenvinke.nl:443/update/win32/"
"info","updater","2016-09-22T18:12:16.075Z","checking for updates now"
"info","updater","2016-09-22T18:12:16.075Z","checking-for-update"
"info","application-state","2016-09-22T18:12:16.119Z","State saved"
"info","npm-detection","2016-09-22T18:12:28.595Z","found package.json at C:\Users\Daniel\Documents\Entwicklung\js\aurelia\try-aurelia-webpack-materialize\package.json"
"info","aurelia-cli-detection","2016-09-22T18:12:28.598Z","did not find aurelia.json file"
"info","gulp-detection","2016-09-22T18:12:28.600Z","did not find gulpfile"
"info","webpack-detection","2016-09-22T18:12:28.600Z","webpack.config.js found: C:\Users\Daniel\Documents\Entwicklung\js\aurelia\try-aurelia-webpack-materialize\webpack.config.js"
"info","typings-detection","2016-09-22T18:12:28.602Z","did not find typings.json file"
"info","dotnet-detection","2016-09-22T18:12:28.603Z","did not find project.json file"
"info","application-state","2016-09-22T18:12:28.681Z","State saved"
"info","project-manager","2016-09-22T18:12:28.683Z","Project added"
"info","application-state","2016-09-22T18:12:28.720Z","State saved"
"info","TaskManager","2016-09-22T18:12:49.115Z","queued 'NPM install' for project 'try-aurelia-skeleton-webpack-materialize'"
"info","TaskManager","2016-09-22T18:12:49.116Z","started 'NPM install' for project 'try-aurelia-skeleton-webpack-materialize'"
"info","updater","2016-09-22T18:15:24.960Z","A new update is available"
"info","notification","2016-09-22T18:19:50.749Z","Version 0.4.1 has been downloaded and will be automatically installed on Quit"
"info","TaskManager","2016-09-22T18:23:50.701Z","task 'NPM install' for project 'try-aurelia-skeleton-webpack-materialize' finished without error"
"info","TaskManager","2016-09-22T18:24:44.346Z","queued 'npm start' for project 'try-aurelia-skeleton-webpack-materialize'"
"info","TaskManager","2016-09-22T18:24:44.346Z","started 'npm start' for project 'try-aurelia-skeleton-webpack-materialize'"
"info","notification","2016-09-22T18:24:44.365Z","Started"
"info","TaskManager","2016-09-22T18:24:46.314Z","task 'npm start' for project 'try-aurelia-skeleton-webpack-materialize' finished without error"
"info","application-state","2016-09-22T18:24:51.357Z","State saved"
"info","TaskManager","2016-09-22T18:25:54.227Z","queued 'NPM install' for project 'try-aurelia-skeleton-webpack-materialize'"
"info","TaskManager","2016-09-22T18:25:54.228Z","started 'NPM install' for project 'try-aurelia-skeleton-webpack-materialize'"
"info","TaskManager","2016-09-22T18:27:13.385Z","task 'NPM install' for project 'try-aurelia-skeleton-webpack-materialize' finished without error"

```

**Comment by JeroenVinke** [comment] 2016-09-28 06:44
I believe the UX of the taskmanager has improved a lot. Tasks that have failed are always visible in the taskmanager now, and all dependent tasks will be stopped. That allows you to inspect what went wrong atleast. So I'll close this issue as we do not have an error message to go on

**Closed by JeroenVinke** 2016-09-28 06:44 UTC
